name: hourly-updater

on:
  schedule:
    - cron: '15 * * * *'   
  workflow_dispatch:       

jobs:
  run-updater:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        # if your backend code is in a subfolder (e.g. "backend/"), add:
        # working-directory: backend

      - name: Run updater script
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          OPENAQ_API_KEY: ${{ secrets.OPENAQ_API_KEY }}
          SENSOR_IDS: ${{ secrets.SENSOR_IDS }}   # comma separated or JSON list
        run: |
          # run the one-off script (adjust the filename if needed)
          python update_and_push.py
        # working-directory: backend   # uncomment if your script sits in subfolder
